"""initial schema

Revision ID: 3b985ec2c3da
Revises: 
Create Date: 2026-09-10 15:26:14.809204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b985ec2c3da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('auth_provider', sa.String(length=20), nullable=False),
    sa.Column('auth_provider_id', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('leagues',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('invite_code', sa.String(length=10), nullable=False),
    sa.Column('admin_user_id', sa.Uuid(), nullable=False),
    sa.Column('budget_per_gameweek', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_invite_code'), 'leagues', ['invite_code'], unique=True)
    op.create_table('user_xp',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('league_memberships',
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='membershiprole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('league_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.String(length=280), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('seasons',
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('champion_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['champion_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_streaks',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('streak_type', sa.Enum('TOP_3_FINISH', 'CORRECT_PICKS', name='streaktype'), nullable=False),
    sa.Column('current_count', sa.Integer(), nullable=False),
    sa.Column('best_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'league_id', 'streak_type', name='uq_user_streak')
    )
    op.create_table('gameweeks',
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('opens_at', sa.DateTime(), nullable=False),
    sa.Column('locks_at', sa.DateTime(), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'OPEN', 'LOCKED', 'SETTLED', name='gameweekstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenges',
    sa.Column('gameweek_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('gameweek_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('competition', sa.String(length=120), nullable=False),
    sa.Column('home_team', sa.String(length=120), nullable=False),
    sa.Column('away_team', sa.String(length=120), nullable=False),
    sa.Column('kickoff_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'FINISHED', 'POSTPONED', name='matchstatus'), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('result', sa.Enum('HOME', 'DRAW', 'AWAY', name='matchoutcome'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_external_id'), 'matches', ['external_id'], unique=False)
    op.create_table('user_badges',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('badge_id', sa.Uuid(), nullable=False),
    sa.Column('gameweek_id', sa.Uuid(), nullable=True),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'league_id', 'badge_id', 'gameweek_id', name='uq_user_badge')
    )
    op.create_table('wallets',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('gameweek_id', sa.Uuid(), nullable=False),
    sa.Column('starting_balance', sa.Integer(), nullable=False),
    sa.Column('current_balance', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'league_id', 'gameweek_id', name='uq_wallet_user_league_gameweek')
    )
    op.create_table('odds_snapshots',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('market', sa.Enum('WINNER', 'DOUBLE_CHANCE', 'OVER_UNDER', 'BOTH_TEAMS_TO_SCORE', name='market'), nullable=False),
    sa.Column('selection', sa.Enum('HOME', 'DRAW', 'AWAY', 'HOME_OR_DRAW', 'AWAY_OR_DRAW', 'HOME_OR_AWAY', 'OVER', 'UNDER', 'YES', 'NO', name='selection'), nullable=False),
    sa.Column('line', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_snapshots_fetched_at'), 'odds_snapshots', ['fetched_at'], unique=False)
    op.create_table('predictions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('gameweek_id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('market', sa.Enum('WINNER', 'DOUBLE_CHANCE', 'OVER_UNDER', 'BOTH_TEAMS_TO_SCORE', name='market'), nullable=False),
    sa.Column('selection', sa.Enum('HOME', 'DRAW', 'AWAY', 'HOME_OR_DRAW', 'AWAY_OR_DRAW', 'HOME_OR_AWAY', 'OVER', 'UNDER', 'YES', 'NO', name='selection'), nullable=False),
    sa.Column('line', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('odds_price_at_pick', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('stake', sa.Integer(), nullable=False),
    sa.Column('potential_payout', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'WON', 'LOST', 'VOID', name='predictionstatus'), nullable=False),
    sa.Column('payout', sa.Integer(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'league_id', 'match_id', name='uq_prediction_user_league_match')
    )
    op.create_table('user_challenges',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('challenge_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='challengestatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'challenge_id', name='uq_user_challenge')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_challenges')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_odds_snapshots_fetched_at'), table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_table('wallets')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_matches_external_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_table('challenges')
    op.drop_table('gameweeks')
    op.drop_table('user_streaks')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('league_memberships')
    op.drop_table('user_xp')
    op.drop_index(op.f('ix_leagues_invite_code'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('badges')
    # ### end Alembic commands ###
