"""add staff flag and failed jobs table

Revision ID: 70e11a2952e6
Revises: e036a7f4d83a
Create Date: 2026-09-12 15:55:57.893411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e11a2952e6'
down_revision: Union[str, None] = 'e036a7f4d83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_jobs',
    sa.Column('job_name', sa.String(length=80), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_jobs_job_name'), 'failed_jobs', ['job_name'], unique=False)
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_staff')
    op.drop_index(op.f('ix_failed_jobs_job_name'), table_name='failed_jobs')
    op.drop_table('failed_jobs')
    # ### end Alembic commands ###
