"""add gameweek deadline reminder flag

Revision ID: e036a7f4d83a
Revises: 2c9df7a57459
Create Date: 2026-09-12 15:51:30.254058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e036a7f4d83a'
down_revision: Union[str, None] = '2c9df7a57459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'gameweeks',
        sa.Column('deadline_reminder_sent', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gameweeks', 'deadline_reminder_sent')
    # ### end Alembic commands ###
